version: '3'

services:
  nextcloud:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS=localhost
      - NEXTCLOUD_DB_HOST=db
      - ONLYOFFICE_DOCUMENT_SERVER_HOST=localhost
      - ONLYOFFICE_DOCUMENT_SERVER_PORT=8082
      - COLLABORA_SERVER_URL=http://172.21.0.3:9980
    volumes:
      - ./nextcloud:/var/www/html
    depends_on:
      - db
      - onlyoffice
      - collabora

  onlyoffice:
    image: onlyoffice/documentserver
    ports:
      - 8082:80
    environment:
      - JWT_ENABLED=true
      - JWT_SECRET=auth123

  collabora:
    image: collabora/code
    restart: always
    ports:
      - "9980:9980"
    environment:
      - extra_params=--o:ssl.enable=false
    cap_add:
      - MKNOD

  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=auth123
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=auth123
    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8081:80
    depends_on:
      - db

  nginx-proxy:
    image: nginx
    container_name: nginx-proxy
    ports:
      - "80:80"

networks:
  default:
    external:
      name: nginx-proxy
  proxy:
    external: true
