version: '3'

services:
  nextcloud:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:80
    environment:
      - NEXTCLOUD_TRUSTED_DOMAINS=localhost
      - NEXTCLOUD_DB_HOST=db
    volumes:
      - ./nextcloud:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=auth123
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=auth123
    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
    ports:
      - 8081:80
    depends_on:
      - db
